export const data = [
  {
    athlete: "Angelo Taylor",
    age: 21,
    country: "United States",
    year: 2000,
    date: "01/10/2000",
    sport: "Athletics",
    gold: 1,
    silver: 0,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Paul Tergat",
    age: 31,
    country: "Kenya",
    year: 2000,
    date: "01/10/2000",
    sport: "Athletics",
    gold: 0,
    silver: 1,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Aikaterini Thanou",
    age: 25,
    country: "Greece",
    year: 2000,
    date: "01/10/2000",
    sport: "Athletics",
    gold: 0,
    silver: 1,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Obadele Thompson",
    age: 24,
    country: "Barbados",
    year: 2000,
    date: "01/10/2000",
    sport: "Athletics",
    gold: 0,
    silver: 0,
    bronze: 1,
    total: 1,
  },
  {
    athlete: "Tesfaye Tola",
    age: 25,
    country: "Ethiopia",
    year: 2000,
    date: "01/10/2000",
    sport: "Athletics",
    gold: 0,
    silver: 0,
    bronze: 1,
    total: 1,
  },
  {
    athlete: "Terrence Trammell",
    age: 21,
    country: "United States",
    year: 2000,
    date: "01/10/2000",
    sport: "Athletics",
    gold: 0,
    silver: 1,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Derartu Tulu",
    age: 28,
    country: "Ethiopia",
    year: 2000,
    date: "01/10/2000",
    sport: "Athletics",
    gold: 1,
    silver: 0,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Kjersti Tysse-Plätzer",
    age: 28,
    country: "Norway",
    year: 2000,
    date: "01/10/2000",
    sport: "Athletics",
    gold: 0,
    silver: 1,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Enefiok Udo-Obong",
    age: 18,
    country: "Nigeria",
    year: 2000,
    date: "01/10/2000",
    sport: "Athletics",
    gold: 1,
    silver: 0,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "María Vascó",
    age: 24,
    country: "Spain",
    year: 2000,
    date: "01/10/2000",
    sport: "Athletics",
    gold: 0,
    silver: 0,
    bronze: 1,
    total: 1,
  },
  {
    athlete: "Nicola Vizzoni",
    age: 26,
    country: "Italy",
    year: 2000,
    date: "01/10/2000",
    sport: "Athletics",
    gold: 0,
    silver: 1,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Eric Wainaina",
    age: 26,
    country: "Kenya",
    year: 2000,
    date: "01/10/2000",
    sport: "Athletics",
    gold: 0,
    silver: 1,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Wang Liping",
    age: 24,
    country: "China",
    year: 2000,
    date: "01/10/2000",
    sport: "Athletics",
    gold: 1,
    silver: 0,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Bernard Williams III",
    age: 22,
    country: "United States",
    year: 2000,
    date: "01/10/2000",
    sport: "Athletics",
    gold: 1,
    silver: 0,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Chris Williams",
    age: 28,
    country: "Jamaica",
    year: 2000,
    date: "01/10/2000",
    sport: "Athletics",
    gold: 0,
    silver: 1,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Million Wolde",
    age: 21,
    country: "Ethiopia",
    year: 2000,
    date: "01/10/2000",
    sport: "Athletics",
    gold: 1,
    silver: 0,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Irina Yatchenko",
    age: 34,
    country: "Belarus",
    year: 2000,
    date: "01/10/2000",
    sport: "Athletics",
    gold: 0,
    silver: 0,
    bronze: 1,
    total: 1,
  },
  {
    athlete: "Yelena Yelesina",
    age: 30,
    country: "Russia",
    year: 2000,
    date: "01/10/2000",
    sport: "Athletics",
    gold: 1,
    silver: 0,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Jan Železný",
    age: 34,
    country: "Czech Republic",
    year: 2000,
    date: "01/10/2000",
    sport: "Athletics",
    gold: 1,
    silver: 0,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Szymon Ziólkowski",
    age: 24,
    country: "Poland",
    year: 2000,
    date: "01/10/2000",
    sport: "Athletics",
    gold: 1,
    silver: 0,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Ellina Zvereva",
    age: 39,
    country: "Belarus",
    year: 2000,
    date: "01/10/2000",
    sport: "Athletics",
    gold: 1,
    silver: 0,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Olesya Zykina",
    age: 19,
    country: "Russia",
    year: 2000,
    date: "01/10/2000",
    sport: "Athletics",
    gold: 0,
    silver: 0,
    bronze: 1,
    total: 1,
  },
  {
    athlete: "Didier Défago",
    age: 32,
    country: "Switzerland",
    year: 2010,
    date: "28/02/2010",
    sport: "Alpine Skiing",
    gold: 1,
    silver: 0,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Andrea Fischbacher",
    age: 24,
    country: "Austria",
    year: 2010,
    date: "28/02/2010",
    sport: "Alpine Skiing",
    gold: 1,
    silver: 0,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Carlo Janka",
    age: 23,
    country: "Switzerland",
    year: 2010,
    date: "28/02/2010",
    sport: "Alpine Skiing",
    gold: 1,
    silver: 0,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Kjetil Jansrud",
    age: 24,
    country: "Norway",
    year: 2010,
    date: "28/02/2010",
    sport: "Alpine Skiing",
    gold: 0,
    silver: 1,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "André Myhrer",
    age: 27,
    country: "Sweden",
    year: 2010,
    date: "28/02/2010",
    sport: "Alpine Skiing",
    gold: 0,
    silver: 0,
    bronze: 1,
    total: 1,
  },
  {
    athlete: "Anja Pärson",
    age: 28,
    country: "Sweden",
    year: 2010,
    date: "28/02/2010",
    sport: "Alpine Skiing",
    gold: 0,
    silver: 0,
    bronze: 1,
    total: 1,
  },
  {
    athlete: "Giuliano Razzoli",
    age: 25,
    country: "Italy",
    year: 2010,
    date: "28/02/2010",
    sport: "Alpine Skiing",
    gold: 1,
    silver: 0,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Viktoria Rebensburg",
    age: 20,
    country: "Germany",
    year: 2010,
    date: "28/02/2010",
    sport: "Alpine Skiing",
    gold: 1,
    silver: 0,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Marlies Schild",
    age: 28,
    country: "Austria",
    year: 2010,
    date: "28/02/2010",
    sport: "Alpine Skiing",
    gold: 0,
    silver: 1,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Andrew Weibrecht",
    age: 24,
    country: "United States",
    year: 2010,
    date: "28/02/2010",
    sport: "Alpine Skiing",
    gold: 0,
    silver: 0,
    bronze: 1,
    total: 1,
  },
  {
    athlete: "Šárka Záhrobská",
    age: 25,
    country: "Czech Republic",
    year: 2010,
    date: "28/02/2010",
    sport: "Alpine Skiing",
    gold: 0,
    silver: 0,
    bronze: 1,
    total: 1,
  },
  {
    athlete: "Silvan Zurbriggen",
    age: 28,
    country: "Switzerland",
    year: 2010,
    date: "28/02/2010",
    sport: "Alpine Skiing",
    gold: 0,
    silver: 0,
    bronze: 1,
    total: 1,
  },
  {
    athlete: "Kjetil André Aamodt",
    age: 34,
    country: "Norway",
    year: 2006,
    date: "26/02/2006",
    sport: "Alpine Skiing",
    gold: 1,
    silver: 0,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Joël Chenal",
    age: 32,
    country: "France",
    year: 2006,
    date: "26/02/2006",
    sport: "Alpine Skiing",
    gold: 0,
    silver: 1,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Antoine Dénériaz",
    age: 29,
    country: "France",
    year: 2006,
    date: "26/02/2006",
    sport: "Alpine Skiing",
    gold: 1,
    silver: 0,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Reinfried Herbst",
    age: 27,
    country: "Austria",
    year: 2006,
    date: "26/02/2006",
    sport: "Alpine Skiing",
    gold: 0,
    silver: 1,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Ambrosi Hoffmann",
    age: 28,
    country: "Switzerland",
    year: 2006,
    date: "26/02/2006",
    sport: "Alpine Skiing",
    gold: 0,
    silver: 0,
    bronze: 1,
    total: 1,
  },
  {
    athlete: "Nicole Hosp",
    age: 22,
    country: "Austria",
    year: 2006,
    date: "26/02/2006",
    sport: "Alpine Skiing",
    gold: 0,
    silver: 1,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Bruno Kernen",
    age: 33,
    country: "Switzerland",
    year: 2006,
    date: "26/02/2006",
    sport: "Alpine Skiing",
    gold: 0,
    silver: 0,
    bronze: 1,
    total: 1,
  },
  {
    athlete: "Ivica Kostelic",
    age: 26,
    country: "Croatia",
    year: 2006,
    date: "26/02/2006",
    sport: "Alpine Skiing",
    gold: 0,
    silver: 1,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Ted Ligety",
    age: 21,
    country: "United States",
    year: 2006,
    date: "26/02/2006",
    sport: "Alpine Skiing",
    gold: 1,
    silver: 0,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Julia Mancuso",
    age: 21,
    country: "United States",
    year: 2006,
    date: "26/02/2006",
    sport: "Alpine Skiing",
    gold: 1,
    silver: 0,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Alexandra Meissnitzer",
    age: 32,
    country: "Austria",
    year: 2006,
    date: "26/02/2006",
    sport: "Alpine Skiing",
    gold: 0,
    silver: 0,
    bronze: 1,
    total: 1,
  },
  {
    athlete: "Anna Ottosson",
    age: 29,
    country: "Sweden",
    year: 2006,
    date: "26/02/2006",
    sport: "Alpine Skiing",
    gold: 0,
    silver: 0,
    bronze: 1,
    total: 1,
  },
  {
    athlete: "Tanja Poutiainen",
    age: 25,
    country: "Finland",
    year: 2006,
    date: "26/02/2006",
    sport: "Alpine Skiing",
    gold: 0,
    silver: 1,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Martina Schild",
    age: 24,
    country: "Switzerland",
    year: 2006,
    date: "26/02/2006",
    sport: "Alpine Skiing",
    gold: 0,
    silver: 1,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Michael Walchhofer",
    age: 30,
    country: "Austria",
    year: 2006,
    date: "26/02/2006",
    sport: "Alpine Skiing",
    gold: 0,
    silver: 1,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Sébastien Amiez",
    age: 29,
    country: "France",
    year: 2002,
    date: "24/02/2002",
    sport: "Alpine Skiing",
    gold: 0,
    silver: 1,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Daniela Ceccarelli",
    age: 26,
    country: "Italy",
    year: 2002,
    date: "24/02/2002",
    sport: "Alpine Skiing",
    gold: 1,
    silver: 0,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Martina Ertl-Renz",
    age: 28,
    country: "Germany",
    year: 2002,
    date: "24/02/2002",
    sport: "Alpine Skiing",
    gold: 0,
    silver: 0,
    bronze: 1,
    total: 1,
  },
  {
    athlete: "Isolde Kostner",
    age: 26,
    country: "Italy",
    year: 2002,
    date: "24/02/2002",
    sport: "Alpine Skiing",
    gold: 0,
    silver: 1,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Carole Montillet-Carles",
    age: 28,
    country: "France",
    year: 2002,
    date: "24/02/2002",
    sport: "Alpine Skiing",
    gold: 1,
    silver: 0,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Sonja Nef",
    age: 29,
    country: "Switzerland",
    year: 2002,
    date: "24/02/2002",
    sport: "Alpine Skiing",
    gold: 0,
    silver: 0,
    bronze: 1,
    total: 1,
  },
  {
    athlete: "Laure Pequegnot",
    age: 26,
    country: "France",
    year: 2002,
    date: "24/02/2002",
    sport: "Alpine Skiing",
    gold: 0,
    silver: 1,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Karen Putzer",
    age: 23,
    country: "Italy",
    year: 2002,
    date: "24/02/2002",
    sport: "Alpine Skiing",
    gold: 0,
    silver: 0,
    bronze: 1,
    total: 1,
  },
  {
    athlete: "Andreas Schifferer",
    age: 27,
    country: "Austria",
    year: 2002,
    date: "24/02/2002",
    sport: "Alpine Skiing",
    gold: 0,
    silver: 0,
    bronze: 1,
    total: 1,
  },
  {
    athlete: "Fritz Strobl",
    age: 29,
    country: "Austria",
    year: 2002,
    date: "24/02/2002",
    sport: "Alpine Skiing",
    gold: 1,
    silver: 0,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Jean-Pierre Vidal",
    age: 24,
    country: "France",
    year: 2002,
    date: "24/02/2002",
    sport: "Alpine Skiing",
    gold: 1,
    silver: 0,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Mariana Avitia",
    age: 18,
    country: "Mexico",
    year: 2012,
    date: "12/08/2012",
    sport: "Archery",
    gold: 0,
    silver: 0,
    bronze: 1,
    total: 1,
  },
  {
    athlete: "Cheng Ming",
    age: 26,
    country: "China",
    year: 2012,
    date: "12/08/2012",
    sport: "Archery",
    gold: 0,
    silver: 1,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Choi Hyeon-Ju",
    age: 27,
    country: "South Korea",
    year: 2012,
    date: "12/08/2012",
    sport: "Archery",
    gold: 1,
    silver: 0,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Dai Xiaoxiang",
    age: 21,
    country: "China",
    year: 2012,
    date: "12/08/2012",
    sport: "Archery",
    gold: 0,
    silver: 0,
    bronze: 1,
    total: 1,
  },
  {
    athlete: "Brady Ellison",
    age: 23,
    country: "United States",
    year: 2012,
    date: "12/08/2012",
    sport: "Archery",
    gold: 0,
    silver: 1,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Fang Yuting",
    age: 22,
    country: "China",
    year: 2012,
    date: "12/08/2012",
    sport: "Archery",
    gold: 0,
    silver: 1,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Michele Frangilli",
    age: 36,
    country: "Italy",
    year: 2012,
    date: "12/08/2012",
    sport: "Archery",
    gold: 1,
    silver: 0,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Takaharu Furukawa",
    age: 27,
    country: "Japan",
    year: 2012,
    date: "12/08/2012",
    sport: "Archery",
    gold: 0,
    silver: 1,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Marco Galiazzo",
    age: 29,
    country: "Italy",
    year: 2012,
    date: "12/08/2012",
    sport: "Archery",
    gold: 1,
    silver: 0,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Ren Hayakawa",
    age: 24,
    country: "Japan",
    year: 2012,
    date: "12/08/2012",
    sport: "Archery",
    gold: 0,
    silver: 0,
    bronze: 1,
    total: 1,
  },
  {
    athlete: "Im Dong-Hyeon",
    age: 27,
    country: "South Korea",
    year: 2012,
    date: "12/08/2012",
    sport: "Archery",
    gold: 0,
    silver: 0,
    bronze: 1,
    total: 1,
  },
  {
    athlete: "Jake Kaminski",
    age: 23,
    country: "United States",
    year: 2012,
    date: "12/08/2012",
    sport: "Archery",
    gold: 0,
    silver: 1,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Miki Kanie",
    age: 23,
    country: "Japan",
    year: 2012,
    date: "12/08/2012",
    sport: "Archery",
    gold: 0,
    silver: 0,
    bronze: 1,
    total: 1,
  },
  {
    athlete: "Kaori Kawanaka",
    age: 20,
    country: "Japan",
    year: 2012,
    date: "12/08/2012",
    sport: "Archery",
    gold: 0,
    silver: 0,
    bronze: 1,
    total: 1,
  },
  {
    athlete: "Kim Bub-Min",
    age: 21,
    country: "South Korea",
    year: 2012,
    date: "12/08/2012",
    sport: "Archery",
    gold: 0,
    silver: 0,
    bronze: 1,
    total: 1,
  },
  {
    athlete: "Lee Seong-Jin",
    age: 27,
    country: "South Korea",
    year: 2012,
    date: "12/08/2012",
    sport: "Archery",
    gold: 1,
    silver: 0,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Mauro Nespoli",
    age: 24,
    country: "Italy",
    year: 2012,
    date: "12/08/2012",
    sport: "Archery",
    gold: 1,
    silver: 0,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Aída Román",
    age: 24,
    country: "Mexico",
    year: 2012,
    date: "12/08/2012",
    sport: "Archery",
    gold: 0,
    silver: 1,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Jacob Wukie",
    age: 26,
    country: "United States",
    year: 2012,
    date: "12/08/2012",
    sport: "Archery",
    gold: 0,
    silver: 1,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Xu Jing",
    age: 21,
    country: "China",
    year: 2012,
    date: "12/08/2012",
    sport: "Archery",
    gold: 0,
    silver: 1,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Virginie Arnold",
    age: 28,
    country: "France",
    year: 2008,
    date: "24/08/2008",
    sport: "Archery",
    gold: 0,
    silver: 0,
    bronze: 1,
    total: 1,
  },
  {
    athlete: "Bair Badyonov",
    age: 32,
    country: "Russia",
    year: 2008,
    date: "24/08/2008",
    sport: "Archery",
    gold: 0,
    silver: 0,
    bronze: 1,
    total: 1,
  },
  {
    athlete: "Chen Ling",
    age: 21,
    country: "China",
    year: 2008,
    date: "24/08/2008",
    sport: "Archery",
    gold: 0,
    silver: 1,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Ilario Di Buò",
    age: 51,
    country: "Italy",
    year: 2008,
    date: "24/08/2008",
    sport: "Archery",
    gold: 0,
    silver: 1,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Sophie Dodémont",
    age: 34,
    country: "France",
    year: 2008,
    date: "24/08/2008",
    sport: "Archery",
    gold: 0,
    silver: 0,
    bronze: 1,
    total: 1,
  },
  {
    athlete: "Marco Galiazzo",
    age: 25,
    country: "Italy",
    year: 2008,
    date: "24/08/2008",
    sport: "Archery",
    gold: 0,
    silver: 1,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Guo Dan",
    age: 22,
    country: "China",
    year: 2008,
    date: "24/08/2008",
    sport: "Archery",
    gold: 0,
    silver: 1,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Im Dong-Hyeon",
    age: 23,
    country: "South Korea",
    year: 2008,
    date: "24/08/2008",
    sport: "Archery",
    gold: 1,
    silver: 0,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Jiang Lin",
    age: 26,
    country: "China",
    year: 2008,
    date: "24/08/2008",
    sport: "Archery",
    gold: 0,
    silver: 0,
    bronze: 1,
    total: 1,
  },
  {
    athlete: "Joo Hyun-Jung",
    age: 26,
    country: "South Korea",
    year: 2008,
    date: "24/08/2008",
    sport: "Archery",
    gold: 1,
    silver: 0,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Lee Chang-Hwan",
    age: 26,
    country: "South Korea",
    year: 2008,
    date: "24/08/2008",
    sport: "Archery",
    gold: 1,
    silver: 0,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Li Wenquan",
    age: 22,
    country: "China",
    year: 2008,
    date: "24/08/2008",
    sport: "Archery",
    gold: 0,
    silver: 0,
    bronze: 1,
    total: 1,
  },
  {
    athlete: "Mauro Nespoli",
    age: 20,
    country: "Italy",
    year: 2008,
    date: "24/08/2008",
    sport: "Archery",
    gold: 0,
    silver: 1,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Viktor Ruban",
    age: 27,
    country: "Ukraine",
    year: 2008,
    date: "24/08/2008",
    sport: "Archery",
    gold: 1,
    silver: 0,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Bérengère Schuh",
    age: 24,
    country: "France",
    year: 2008,
    date: "24/08/2008",
    sport: "Archery",
    gold: 0,
    silver: 0,
    bronze: 1,
    total: 1,
  },
  {
    athlete: "Xue Haifeng",
    age: 28,
    country: "China",
    year: 2008,
    date: "24/08/2008",
    sport: "Archery",
    gold: 0,
    silver: 0,
    bronze: 1,
    total: 1,
  },
  {
    athlete: "Chen Li-Ju",
    age: 23,
    country: "Chinese Taipei",
    year: 2004,
    date: "29/08/2004",
    sport: "Archery",
    gold: 0,
    silver: 0,
    bronze: 1,
    total: 1,
  },
  {
    athlete: "Chen Szu-Yuan",
    age: 23,
    country: "Chinese Taipei",
    year: 2004,
    date: "29/08/2004",
    sport: "Archery",
    gold: 0,
    silver: 1,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Tim Cuddihy",
    age: 17,
    country: "Australia",
    year: 2004,
    date: "29/08/2004",
    sport: "Archery",
    gold: 0,
    silver: 0,
    bronze: 1,
    total: 1,
  },
  {
    athlete: "Marco Galiazzo",
    age: 21,
    country: "Italy",
    year: 2004,
    date: "29/08/2004",
    sport: "Archery",
    gold: 1,
    silver: 0,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "He Ying",
    age: 27,
    country: "China",
    year: 2004,
    date: "29/08/2004",
    sport: "Archery",
    gold: 0,
    silver: 1,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Dmytro Hrachov",
    age: 20,
    country: "Ukraine",
    year: 2004,
    date: "29/08/2004",
    sport: "Archery",
    gold: 0,
    silver: 0,
    bronze: 1,
    total: 1,
  },
  {
    athlete: "Im Dong-Hyeon",
    age: 19,
    country: "South Korea",
    year: 2004,
    date: "29/08/2004",
    sport: "Archery",
    gold: 1,
    silver: 0,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Jang Yong-Ho",
    age: 28,
    country: "South Korea",
    year: 2004,
    date: "29/08/2004",
    sport: "Archery",
    gold: 1,
    silver: 0,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Lin Sang",
    age: 26,
    country: "China",
    year: 2004,
    date: "29/08/2004",
    sport: "Archery",
    gold: 0,
    silver: 1,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Liu Ming-Huang",
    age: 19,
    country: "Chinese Taipei",
    year: 2004,
    date: "29/08/2004",
    sport: "Archery",
    gold: 0,
    silver: 1,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Park Gyeong-Mo",
    age: 28,
    country: "South Korea",
    year: 2004,
    date: "29/08/2004",
    sport: "Archery",
    gold: 1,
    silver: 0,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Viktor Ruban",
    age: 23,
    country: "Ukraine",
    year: 2004,
    date: "29/08/2004",
    sport: "Archery",
    gold: 0,
    silver: 0,
    bronze: 1,
    total: 1,
  },
  {
    athlete: "Oleksandr Serdiuk",
    age: 26,
    country: "Ukraine",
    year: 2004,
    date: "29/08/2004",
    sport: "Archery",
    gold: 0,
    silver: 0,
    bronze: 1,
    total: 1,
  },
  {
    athlete: "Wang Cheng-Pang",
    age: 17,
    country: "Chinese Taipei",
    year: 2004,
    date: "29/08/2004",
    sport: "Archery",
    gold: 0,
    silver: 1,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Alison Williamson",
    age: 32,
    country: "Great Britain",
    year: 2004,
    date: "29/08/2004",
    sport: "Archery",
    gold: 0,
    silver: 0,
    bronze: 1,
    total: 1,
  },
  {
    athlete: "Wu Hui-Ju",
    age: 21,
    country: "Chinese Taipei",
    year: 2004,
    date: "29/08/2004",
    sport: "Archery",
    gold: 0,
    silver: 0,
    bronze: 1,
    total: 1,
  },
  {
    athlete: "Hiroshi Yamamoto",
    age: 41,
    country: "Japan",
    year: 2004,
    date: "29/08/2004",
    sport: "Archery",
    gold: 0,
    silver: 1,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Yuan Shu-Chi",
    age: 19,
    country: "Chinese Taipei",
    year: 2004,
    date: "29/08/2004",
    sport: "Archery",
    gold: 0,
    silver: 0,
    bronze: 1,
    total: 1,
  },
  {
    athlete: "Yun Mi-Jin",
    age: 21,
    country: "South Korea",
    year: 2004,
    date: "29/08/2004",
    sport: "Archery",
    gold: 1,
    silver: 0,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Zhang Juanjuan",
    age: 23,
    country: "China",
    year: 2004,
    date: "29/08/2004",
    sport: "Archery",
    gold: 0,
    silver: 1,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Matteo Bisiani",
    age: 24,
    country: "Italy",
    year: 2000,
    date: "01/10/2000",
    sport: "Archery",
    gold: 0,
    silver: 1,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Nataliya Burdeina",
    age: 26,
    country: "Ukraine",
    year: 2000,
    date: "01/10/2000",
    sport: "Archery",
    gold: 0,
    silver: 1,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Ilario Di Buò",
    age: 43,
    country: "Italy",
    year: 2000,
    date: "01/10/2000",
    sport: "Archery",
    gold: 0,
    silver: 1,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Simon Fairweather",
    age: 30,
    country: "Australia",
    year: 2000,
    date: "01/10/2000",
    sport: "Archery",
    gold: 1,
    silver: 0,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Michele Frangilli",
    age: 24,
    country: "Italy",
    year: 2000,
    date: "01/10/2000",
    sport: "Archery",
    gold: 0,
    silver: 1,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Jang Yong-Ho",
    age: 24,
    country: "South Korea",
    year: 2000,
    date: "01/10/2000",
    sport: "Archery",
    gold: 1,
    silver: 0,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Butch Johnson",
    age: 45,
    country: "United States",
    year: 2000,
    date: "01/10/2000",
    sport: "Archery",
    gold: 0,
    silver: 0,
    bronze: 1,
    total: 1,
  },
  {
    athlete: "Kim Cheong-Tae",
    age: 20,
    country: "South Korea",
    year: 2000,
    date: "01/10/2000",
    sport: "Archery",
    gold: 1,
    silver: 0,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Barbara Mensing",
    age: 39,
    country: "Germany",
    year: 2000,
    date: "01/10/2000",
    sport: "Archery",
    gold: 0,
    silver: 0,
    bronze: 1,
    total: 1,
  },
  {
    athlete: "O Gyo-Mun",
    age: 28,
    country: "South Korea",
    year: 2000,
    date: "01/10/2000",
    sport: "Archery",
    gold: 1,
    silver: 0,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Cornelia Pfohl",
    age: 29,
    country: "Germany",
    year: 2000,
    date: "01/10/2000",
    sport: "Archery",
    gold: 0,
    silver: 0,
    bronze: 1,
    total: 1,
  },
  {
    athlete: "Olena Sadovnycha",
    age: 32,
    country: "Ukraine",
    year: 2000,
    date: "01/10/2000",
    sport: "Archery",
    gold: 0,
    silver: 1,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Kateryna Serdiuk",
    age: 17,
    country: "Ukraine",
    year: 2000,
    date: "01/10/2000",
    sport: "Archery",
    gold: 0,
    silver: 1,
    bronze: 0,
    total: 1,
  },
  {
    athlete: "Wietse van Alten",
    age: 21,
    country: "Netherlands",
    year: 2000,
    date: "01/10/2000",
    sport: "Archery",
    gold: 0,
    silver: 0,
    bronze: 1,
    total: 1,
  },
  {
    athlete: "Sandra Wagner-Sachse",
    age: 31,
    country: "Germany",
    year: 2000,
    date: "01/10/2000",
    sport: "Archery",
    gold: 0,
    silver: 0,
    bronze: 1,
    total: 1,
  },
  {
    athlete: "Rod White",
    age: 23,
    country: "United States",
    year: 2000,
    date: "01/10/2000",
    sport: "Archery",
    gold: 0,
    silver: 0,
    bronze: 1,
    total: 1,
  },
];
